In [1]:
import numpy as np
import pandas as pd

# Creating a DataFrame 
pd.DataFrame()

In [ ]:
#dict
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [4]:
#list
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df1 = pd.DataFrame(data_list)
df1

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

# Given custom column names

In [9]:
columns = ["Name", "Age", "City", "Salary"]
custom_column=pd.DataFrame(data_list, columns=columns)
custom_column

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# selection and indexing of columns
x=0, y=1

In [11]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# select using column names = df['column name], multiple column= df[["","",""]]

In [14]:
c_name = df['Name']
mulc_name = df[['Age','City','Salary']]

c_name, mulc_name

(0     John
 1     Anna
 2    Peter
 3    Linda
 Name: Name, dtype: str,
    Age      City  Salary
 0   28  New York   65000
 1   34     Paris   70000
 2   29    Berlin   62000
 3   42    London   85000)

# creating new column = df['column name'] =[values]

In [15]:
df['Designation']=["Doctor","Eng.","Doctor","Eng."]
df

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

# removing column names = df.drop(column name, axis), axis not given by default 0 means x axis, which is row wise.
# multiple column drop = df.drop([column names])

In [17]:
df.drop('Designation', axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#  we remove column but it is not removed from original DF, so need to use inplace.

In [18]:
df

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [19]:
df.drop('Designation', axis=1, inplace=True)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [20]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# remove row = df.drop(row, axis=0)

In [21]:
df.drop(0,axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

# selecting / Accessing rows = use df.loc[index], multiple=df.loc[[indexs]]
# iloc= index location

In [23]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [24]:
row=df.iloc[0]
row

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [25]:
row1 = df.loc[[1,2]]
row1

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000

# Selecting Subsets(some portion) of Rows and Columns = df.loc[[row]][[column names]]

In [26]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:
df.loc[0]['Name']

'John'

In [32]:
df.loc[[0]][['Name']]

   Name
0  John

In [33]:
df.loc[[1,3]][["Age","City"]]

   Age    City
1   34   Paris
3   42  London

# Conditional Selection = means selection based on >,<,>=,<=

In [34]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [35]:
#I only want to see those people whose age is above 30
df[df["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [37]:
#I only want poeple whose age is above 30 and their city must be paris
df[(df["Age"] > 30) & (df["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000