In [1]:
import numpy as np
import pandas as pd

# Finding Missing Data = isna()

In [ ]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

d1 = pd.DataFrame(data)
d1

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [4]:
d1.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

# count of missing or null values =isna().sum()= gives columwise count

In [5]:
d1.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

# tell all the columns have null value or not = isna().any()

In [6]:
d1.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

# Removing Missing Data = dropna() = work row wise, all rows removed where null values are given.

In [7]:
d1

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [8]:
d1.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

# thresh = value => whatever value is written at least that much not null value needed. If nit then row removed.

In [10]:
d1.dropna(thresh = 3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

# Filling the missing Data = fillna(value) = column wise selection.

In [11]:
d1

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [12]:
d1.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

# fill different values for each column

In [13]:
values = {'A': 1, 'B': 2, 'C': 3, 'D': 4}
d1.fillna(value=values)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  4.0
2  1.0  3  3.0  4.0
3  4.0  4  3.0  4.0
4  5.0  5  3.0  5.0

# fill mean value = fillna(d1.mean())

In [14]:
d1.fillna(d1.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0