In [1]:
import numpy as np
import pandas as pd

# iloc vs loc
iloc → "Give me the data at this POSITION"
loc  → "Give me the data with this LABEL / CONDITION"

In [2]:
data = {
    "Name": ["Amit", "Neha", "Rahul", "Priya", "Sneha", "Vikas"],
    "Age": [22, 19, 25, 21, 28, 18],
    "City": ["Pune", "Mumbai", "Pune", "Delhi", "Mumbai", "Pune"],
    "Salary": [30000, 25000, 45000, 35000, 50000, 22000]
}

df1 = pd.DataFrame(data)
df1

    Name  Age    City  Salary
0   Amit   22    Pune   30000
1   Neha   19  Mumbai   25000
2  Rahul   25    Pune   45000
3  Priya   21   Delhi   35000
4  Sneha   28  Mumbai   50000
5  Vikas   18    Pune   22000

Practice — 5 Questions

Q1. Get the first 3 rows of the DataFrame.

Q2. Get the row where the index is 4.

Q3. Get all people whose age is greater than 20.

Q4. Get only the Name of people whose salary is greater than 30,000.

Q5. Get the Name and Salary of the first 4 rows. first 4 rows = position

In [3]:
df1.iloc[:3]

    Name  Age    City  Salary
0   Amit   22    Pune   30000
1   Neha   19  Mumbai   25000
2  Rahul   25    Pune   45000

In [4]:
df1.loc[4]

Name       Sneha
Age           28
City      Mumbai
Salary     50000
Name: 4, dtype: object

In [5]:
df1.loc[df1["Age"] > 20, "Name"]

0     Amit
2    Rahul
3    Priya
4    Sneha
Name: Name, dtype: str

In [6]:
df1.loc[df1["Salary"] > 30000, "Name"]

2    Rahul
3    Priya
4    Sneha
Name: Name, dtype: str

In [7]:
# df1.iloc[:4] [['Name', 'Salary']]
df1.iloc[:4, [0, 3]]

    Name  Salary
0   Amit   30000
1   Neha   25000
2  Rahul   45000
3  Priya   35000

Q1. Get the last 2 rows of the DataFrame.

Q2. Get the Name and City of the person whose index is 2.

Q3. Get all rows where the City is Pune.

Q4. Get the Name and Age of people whose salary is less than 35,000.

Q5. Get the Age and Salary columns for rows at positions 1, 2, and 3.

In [8]:
df1

    Name  Age    City  Salary
0   Amit   22    Pune   30000
1   Neha   19  Mumbai   25000
2  Rahul   25    Pune   45000
3  Priya   21   Delhi   35000
4  Sneha   28  Mumbai   50000
5  Vikas   18    Pune   22000

In [9]:
df1.iloc[-2:]

    Name  Age    City  Salary
4  Sneha   28  Mumbai   50000
5  Vikas   18    Pune   22000

In [10]:
df1.loc[2, ['Name', 'City']]

Name    Rahul
City     Pune
Name: 2, dtype: str

In [11]:
df1.loc[df1['City'] == 'Pune']

    Name  Age  City  Salary
0   Amit   22  Pune   30000
2  Rahul   25  Pune   45000
5  Vikas   18  Pune   22000

In [12]:
df1.loc[df1['Salary'] < 35000, ['Name', 'Age']]

    Name  Age
0   Amit   22
1   Neha   19
5  Vikas   18

In [13]:
df1.iloc[1:4, [1,3]]

   Age  Salary
1   19   25000
2   25   45000
3   21   35000

# Level 1 — Basic DataFrame :
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())

In [14]:
# load file
df=pd.read_csv('Countries.csv')
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [15]:
df.tail()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.2605,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.0000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.0602,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.5660,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [16]:
df.shape

(194, 64)

In [17]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='str')

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    str
 1   country_long                             194 non-null    str
 2   currency                                 194 non-null    str
 3   capital_city                             194 non-null    str
 4   region                                   194 non-null    str
 5   continent                                194 non-null    str
 6   demonym                                  194 non-null    str
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    str
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    str
 63  title                                    187 non-null    str
dtypes: float64(48), int64(6), str(10)
memory usage: 97.1 KB

In [19]:
df.describe()

,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,...,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,median_age
count,194.000000,194.000000,1.930000e+02,1.940000e+02,1.940000e+02,1.940000e+02,194.000000,120.000000,156.000000,1.930000e+02,...,194.000000,1.940000e+02,1.940000e+02,1.940000e+02,193.000000,1.940000e+02,1.940000e+02,194.000000,194.000000,194.000000
mean,18.975601,22.027491,2.454551e+05,2.086784e+05,6.675087e+05,6.563711e+05,9777.116531,66.759366,30.051403,5.144851e+11,...,-51.407216,2.028316e+07,2.050572e+07,4.078888e+07,25.022994,1.763322e+07,2.315566e+07,2.539330,4.644536,25.661856
std,23.876225,66.396389,6.356268e+05,7.824926e+05,1.837107e+06,1.811169e+06,42301.458421,71.806247,26.740880,2.307148e+12,...,94525.968598,7.258941e+07,7.607158e+07,1.486470e+08,12.671044,7.664187e+07,7.940393e+07,1.800128,2.818297,9.415569
min,-41.000000,-175.000000,4.000000e+00,0.000000e+00,2.027000e+00,3.495450e-02,0.000000,0.000000,0.000267,6.034940e+07,...,-525116.000000,5.513000e+03,5.799000e+03,1.131200e+04,0.000000,0.000000e+00,5.717000e+03,0.000000,0.000000,10.500000
25%,4.000000,-5.000000,6.464000e+03,3.331775e+03,2.355250e+04,2.186562e+04,359.618250,31.951300,18.371875,1.181390e+10,...,-12242.250000,1.036218e+06,1.044902e+06,2.106358e+06,15.384600,5.896640e+05,1.222244e+06,1.525000,2.722500,16.950000
50%,16.583333,21.500000,3.872780e+04,2.528925e+04,1.203750e+05,1.159945e+05,1645.170000,55.426850,27.337750,4.115390e+10,...,-970.000000,4.502713e+06,4.450049e+06,9.125614e+06,25.252500,2.512382e+06,4.508837e+06,2.400000,5.050000,24.950000
75%,40.000000,50.162500,2.150000e+05,1.236735e+05,5.237000e+05,4.911505e+05,4054.022500,79.539300,35.083500,2.519450e+11,...,2904.250000,1.526606e+07,1.478872e+07,3.031361e+07,33.636400,1.133354e+07,1.621355e+07,2.925000,6.967500,34.050000
max,65.000000,178.000000,5.285080e+06,8.153120e+06,1.637690e+07,1.622420e+07,522345.000000,687.994000,310.443000,2.546270e+13,...,561580.000000,6.915285e+08,7.311805e+08,1.417173e+09,61.250000,9.088048e+08,8.975784e+08,10.000000,9.870000,50.500000

Level 2 — Selecting data
1. one column selection = df["Name"]

2. multiple column selection = df[["Name", "Age"]]

3.  integer POSITION = df.iloc[0]

4. by using slicing = df.iloc[0:5]

5.  LABEL / CONDITION, boolean condition = df.loc[df["Age"] > 20]

# see above examples of iloxc vs loc for selecting data

# Level 3 — Cleaning Data
df.isnull()
df.isnull().sum()
df.fillna(0)

df[df["country"].duplicated()]
df["country"].duplicated().sum()
df.drop_duplicates()
df.dropna()

df["Age"].astype(int)

df.rename()
df.replace()

In [20]:
df.isnull().sum()

country             0
country_long        0
currency            0
capital_city        0
region              0
                   ..
democracy_score     0
democracy_type      0
median_age          0
political_leader    7
title               7
Length: 64, dtype: int64

In [21]:
df["country"].duplicated().sum()

np.int64(0)

In [22]:
df[df["country"].duplicated()]

Empty DataFrame
Columns: [country, country_long, currency, capital_city, region, continent, demonym, latitude, longitude, agricultural_land, forest_area, land_area, rural_land, urban_land, central_government_debt_pct_gdp, expense_pct_gdp, gdp, inflation, self_employed_pct, tax_revenue_pct_gdp, unemployment_pct, vulnerable_employment_pct, electricity_access_pct, alternative_nuclear_energy_pct, electricty_production_coal_pct, electricty_production_hydroelectric_pct, electricty_production_gas_pct, electricty_production_nuclear_pct, electricty_production_oil_pct, electricty_production_renewable_pct, energy_imports_pct, fossil_energy_consumption_pct, renewable_energy_consumption_pct, co2_emissions, methane_emissions, nitrous_oxide_emissions, greenhouse_other_emissions, urban_population_under_5m, health_expenditure_pct_gdp, health_expenditure_capita, hospital_beds, hiv_incidence, suicide_rate, armed_forces, internally_displaced_persons, military_expenditure_pct_gdp, birth_rate, death_rate, fertility_rate, internet_pct, life_expectancy, net_migration, population_female, population_male, population, women_parliament_seats_pct, rural_population, urban_population, press, democracy_score, democracy_type, median_age, political_leader, title]
Index: []

[0 rows x 64 columns]

# Level 4 — Sorting & Grouping
df.sort_values("Marks")

df.sort_values("Marks", ascending=False)

# Basic
How many rows are in the dataset?
How many columns are in the dataset?
Display all column names.
How many missing values are present in each column?
What is the average population?

df.isna().any() = It tells you whether each column has at least one missing value.
 df.isna().sum()= "How many missing values does each column have?"
 df.isna().sum().sum() = "How many missing values are there in the entire DataFrame?"

isna()       → identify missing cells
isna().sum() → count missing values
isna().any() → check if missing values exist

In [23]:
# missing values =
df.isna().sum()

country             0
country_long        0
currency            0
capital_city        0
region              0
                   ..
democracy_score     0
democracy_type      0
median_age          0
political_leader    7
title               7
Length: 64, dtype: int64

In [24]:
avg = df['population'].mean()
avg

np.float64(40788877.788659796)

# Filtering
Find countries where population is greater than 100 million.
Find countries where continent is Asia.
Find countries where life_expectancy is greater than 75.
Find countries where unemployment_pct is greater than 10%.
Find countries where internet_pct is greater than 80%.

In [25]:
name = df[df['population'] > 1000000000]['country']
name

34    China
75    India
Name: country, dtype: str

In [26]:
df[df['continent'] == 'Asia']['country']

0                   Afghanistan
7                       Armenia
10                   Azerbaijan
11                      Bahrain
12                   Bangladesh
18                       Bhutan
23                       Brunei
28                     Cambodia
34                        China
44     Dem. People's Rep. Korea
62                      Georgia
75                        India
76                    Indonesia
77                         Iran
78                         Iraq
80                       Israel
83                        Japan
84                       Jordan
85                   Kazakhstan
88                        Korea
89                       Kuwait
90              Kyrgyz Republic
91                      Lao PDR
93                      Lebanon
102                    Malaysia
103                    Maldives
113                    Mongolia
117                     Myanmar
120                       Nepal
128                        Oman
129                    Pakistan
135                 Philippines
138                       Qatar
145                Saudi Arabia
150                   Singapore
158                   Sri Lanka
166        Syrian Arab Republic
167                  Tajikistan
169                    Thailand
172                 Timor-Leste
177                      Turkey
178                Turkmenistan
182        United Arab Emirates
186                  Uzbekistan
189                     Vietnam
190          West Bank and Gaza
191                       Yemen
Name: country, dtype: str

In [27]:
df[df['life_expectancy'] > 75]['country']

1                   Albania
2                   Algeria
5       Antigua and Barbuda
8                 Australia
9                   Austria
11                  Bahrain
13                 Barbados
15                  Belgium
30                   Canada
33                    Chile
34                    China
38               Costa Rica
40                  Croatia
42                   Cyprus
43           Czech Republic
46                  Denmark
55                  Estonia
59                  Finland
60                   France
63                  Germany
65                   Greece
74                  Iceland
79                  Ireland
80                   Israel
81                    Italy
83                    Japan
88                    Korea
89                   Kuwait
97            Liechtenstein
99               Luxembourg
103                Maldives
105                   Malta
121             Netherlands
122             New Zealand
127                  Norway
131                  Panama
136                  Poland
137                Portugal
138                   Qatar
145            Saudi Arabia
150               Singapore
152                Slovenia
157                   Spain
158               Sri Lanka
164                  Sweden
165             Switzerland
169                Thailand
177                  Turkey
182    United Arab Emirates
183          United Kingdom
184           United States
Name: country, dtype: str

In [28]:
df[df['unemployment_pct'] > 10]['country']

0                         Afghanistan
1                             Albania
2                             Algeria
4                              Angola
7                             Armenia
20             Bosnia and Herzegovina
21                           Botswana
27                         Cabo Verde
35                           Colombia
37                              Congo
38                         Costa Rica
47                           Djibouti
56                           Eswatini
61                              Gabon
62                            Georgia
65                             Greece
70                             Guyana
71                              Haiti
77                               Iran
78                               Iraq
84                             Jordan
93                            Lebanon
94                            Lesotho
96                              Libya
107                        Mauritania
114                        Montenegro
115                           Morocco
118                           Namibia
120                             Nepal
126                   North Macedonia
141                            Rwanda
142                             Samoa
144             São Tomé and Principe
154                           Somalia
155                      South Africa
156                       South Sudan
157                             Spain
160                         St. Lucia
161    St. Vincent and the Grenadines
162                             Sudan
170                       The Bahamas
176                           Tunisia
177                            Turkey
190                West Bank and Gaza
191                             Yemen
Name: country, dtype: str

In [29]:
df[df['internet_pct'] >80]['country']

3                   Andorra
5       Antigua and Barbuda
6                 Argentina
8                 Australia
9                   Austria
               ...
177                  Turkey
182    United Arab Emirates
183          United Kingdom
184           United States
185                 Uruguay
Name: country, Length: 78, dtype: str

# Selecting Columns + Filtering
Display only country and population for countries with population greater than 50 million.
Display country, capital_city, and continent for countries in Europe.
Display country and gdp for countries where GDP is greater than 1 trillion.
Display country and life_expectancy where life expectancy is below 60.
Display country, population, and internet_pct for countries where internet usage is above 70%

In [30]:
df[df['population'] > 500000000][['country','population']]

   country  population
34   China  1412175000
75   India  1417173173

In [ ]:
df[df['continent'] == 'Europe'][['country', 'capital_city', 'continent']]

    country      capital_city continent
1   Albania            Tirana    Europe
3   Andorra  Andorra la Vella    Europe
9   Austria            Vienna    Europe
14  Belarus             Minsk    Europe
15  Belgium          Brussels    Europe

In [35]:
df[df['gdp'] > 1000000000000][['country','gdp']]

            country           gdp
8         Australia  1.675420e+12
22           Brazil  1.920100e+12
30           Canada  2.139840e+12
34            China  1.796320e+13
60           France  2.782910e+12
63          Germany  4.072190e+12
75            India  3.385090e+12
76        Indonesia  1.319100e+12
81            Italy  2.010430e+12
83            Japan  4.231140e+12
88            Korea  1.665250e+12
109          Mexico  1.414190e+12
140          Russia  2.240420e+12
145    Saudi Arabia  1.108150e+12
157           Spain  1.397510e+12
183  United Kingdom  3.070670e+12
184   United States  2.546270e+13

In [36]:
df[df['life_expectancy'] < 60][['country','life_expectancy']]

                      country  life_expectancy
25               Burkina Faso             59.0
31   Central African Republic             54.0
32                       Chad             53.0
39              Côte d'Ivoire             59.0
45            Dem. Rep. Congo             59.0
56                   Eswatini             57.0
68                     Guinea             59.0
94                    Lesotho             53.0
104                      Mali             59.0
116                Mozambique             59.0
118                   Namibia             59.0
125                   Nigeria             53.0
154                   Somalia             55.0
156               South Sudan             55.0
193                  Zimbabwe             59.0

In [37]:
df[df['internet_pct'] > 70][['country','population', 'internet_pct']]

                 country  population  internet_pct
1                Albania     2775634       79.3200
2                Algeria    44903225       70.7700
3                Andorra       79824       93.8975
5    Antigua and Barbuda       93763       95.6634
6              Argentina    46234830       87.1507
..                   ...         ...           ...
184        United States   333287557       91.7532
185              Uruguay     3422794       90.0738
186           Uzbekistan    35648100       76.5904
189              Vietnam    98186856       74.2100
190   West Bank and Gaza     5043612       74.6000

[112 rows x 3 columns]

# Sorting
Find the 10 countries with the highest population.
Find the 10 countries with the lowest population.
Find countries with the highest GDP, sorted from highest to lowest.
Sort countries by life_expectancy from highest to lowest.
Sort countries by unemployment_pct from lowest to highest.

In [39]:
df.sort_values(by='population', ascending=False).head(5)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.0,77.0,1790450.0,...,1417173173,14.9446,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister
34,China,People's Republic of China,Chinese yuan,Beijing,Eastern Asia,Asia,Chinese,35.0,105.0,5285080.0,...,1412175000,24.9412,514596570,897578430,0.99,3.32,Authoritarian,34.5,Xi Jinping,General Secretary of the Communist Party
184,United States,United States of America,U.S. dollar,"Washington, D.C.",Northern America,Americas,American,38.0,-97.0,4058100.0,...,333287557,28.7037,56378923,276908634,3.04,7.96,Flawed democracy,33.9,Joe Biden,President
76,Indonesia,Republic of Indonesia,Indonesian rupiah,Jakarta,South-Eastern Asia,Asia,Indonesian,-5.0,120.0,623000.0,...,275501339,21.9130,115892393,159608946,2.13,6.39,Flawed democracy,25.6,Joko Widodo,President
129,Pakistan,Islamic Republic of Pakistan,Pakistani rupee,Islamabad,Southern Asia,Asia,Pakistani,30.0,70.0,367230.0,...,235824862,20.4678,146845783,88979079,1.71,4.17,Hybrid regime,16.5,Imran Khan,Prime Minister

In [41]:
df.sort_values(by='population', ascending=True).head(5)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
179,Tuvalu,Tuvalu,Australian dollar,Funafuti,Polynesia,Oceania,Tuvaluan,-8.000000,178.000000,18.0,...,11312,6.2500,3900,7412,0.0,0.0,Unknown,21.0,Kausea Natano,Prime Minister
119,Nauru,Republic of Nauru,Australian dollar,Yaren,Micronesia,Oceania,Nauruan,-0.533333,166.916667,4.0,...,12668,10.5263,0,12668,0.0,0.0,Unknown,16.3,Lionel Aingimea,President
130,Palau,Republic of Palau,U.S. dollar,Ngerulmud,Micronesia,Oceania,Palauan,7.500000,134.500000,43.0,...,18055,6.2500,3258,14797,0.0,0.0,Unknown,31.7,Thomas Remengesau Jr.,President
143,San Marino,Republic of San Marino,Euro,City of San Marino,Southern Europe,Europe,Sammarinese,43.766667,12.416667,23.0,...,33660,33.3333,763,32897,0.0,0.0,Unknown,42.7,Alessandro Mancini,Captain Regent
112,Monaco,Principality of Monaco,Euro,Monaco,Western Europe,Europe,Monegasque,43.733333,7.400000,NaN,...,36469,33.3333,0,36469,0.0,0.0,Unknown,50.5,Albert II,Sovereign Prince

In [42]:
df.sort_values(by='gdp', ascending=False).head(5)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
184,United States,United States of America,U.S. dollar,"Washington, D.C.",Northern America,Americas,American,38.0,-97.0,4058100.0,...,333287557,28.70370,56378923,276908634,3.04,7.96,Flawed democracy,33.9,Joe Biden,President
34,China,People's Republic of China,Chinese yuan,Beijing,Eastern Asia,Asia,Chinese,35.0,105.0,5285080.0,...,1412175000,24.94120,514596570,897578430,0.99,3.32,Authoritarian,34.5,Xi Jinping,General Secretary of the Communist Party
83,Japan,Japan,Japanese yen,Tokyo,Eastern Asia,Asia,Japanese,36.0,138.0,43720.0,...,125124989,9.91379,10066305,115058684,2.66,7.99,Flawed democracy,44.7,Yoshihide Suga,Prime Minister
63,Germany,Federal Republic of Germany,Euro,Berlin,Western Europe,Europe,German,51.0,9.0,165950.0,...,84079811,34.91850,18793519,65286292,5.36,8.68,Full democracy,40.9,Olaf Scholz,Federal Chancellor
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.0,77.0,1790450.0,...,1417173173,14.94460,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister